### ISSUE TITLE
Failed to create JJTree based parser

### ISSUE THREAD

**Issue by skfcz** [javacc/javacc-8-csharp#1]
Intend : create a JJTree based parser for C#

Environment : Linux , JDK 11

Steps performed: 
 
compiled javacc-8-core
in javacc-8-csharp: mvn install

```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.2.1:install (integration-test-csharp-examples) on project csharp: Execution integration-test-csharp-examples of goal org.apache.maven.plugins:maven-invoker-plugin:3.2.1:install failed: Plugin org.apache.maven.plugins:maven-invoker-plugin:3.2.1 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:0 at specified path /opt/jdk-11.0.3+7/../lib/tools.jar -> [Help 1]
```
This might be  maven setup problem, lib/tools.jar sounds like Java 8.

Tried to run the generation manually:

# Run jjtree ```java -cp csharp-8.0.1-SNAPSHOT.jar:core-8.0.2-SNAPSHOT.jar jjtree
-OUTPUT_DIRECTORY=/home/cz/Projekte/JavaCC/TestProject3/TestProject3
-CODE_GENERATOR=C# examples/JJTreeExamples/eg1/src/main/jjtree/eg1.jjt ```

# Run javacc ```java -cp csharp-8.0.1-SNAPSHOT.jar:core-8.0.2-SNAPSHOT.jar javacc
-OUTPUT_DIRECTORY=/home/cz/Projekte/JavaCC/TestProject3/TestProject3
-CODE_GENERATOR=C#
/home/cz/Projekte/JavaCC/TestProject3/TestProject3/eg1.jj```

# Replace C++ style pointer in parser ```public Node*   Start() {``` to ``` public Node   Start() {```
# Create Node using implementation class  ```Node jjtn000 = new SimpleNode(ParserTreeConstants.JJTEXPRESSION);```
# Add jjtree ```JJTParserState jjtree = new JJTParserState();```
# Add a small test ```TextReader reader = new StringReader("(a + b) * (c + 1);");
Parser parser = new Parser(reader);
var start = parser.Start();```
# Run and get ```System.IndexOutOfRangeException : Index was outside the bounds of the
array.
  at EG1.Parser.MultiplicativeExpression () [0x00134] in
/home/cz/Projekte/JavaCC/TestProject3/TestProject3/Parser.cs:211 
  at EG1.Parser.AdditiveExpression () [0x00114] in
/home/cz/Projekte/JavaCC/TestProject3/TestProject3/Parser.cs:141 
  at EG1.Parser.Expression () [0x0004a] in
/home/cz/Projekte/JavaCC/TestProject3/TestProject3/Parser.cs:75 ```

**Comment by new-javacc** [comment]
So the (known) issue is with:

ERROR_REPORTING

please set that to false and it should work. That option is not very useful anyway.

**Comment by new-javacc** [comment]
Fixed in: https://github.com/javacc/javacc-8-csharp/commit/51c4d7f32b9a7bac6e86ff0dbb1dcdf1d5b269a4
